trigger:
- main

pool:
  name: Default # Nome do agent pool
  demands:
    - Agent.Name -equals LML001  # Força o uso do agente específico - informar o nome do Agente criado
  vmImage: 'windows-latest'

variables:
  resourceGroupName: rg-iac-webapp
  location: centralus
  templateFile: arm-templates/webapp-template.json
  parametersFile: arm-templates/webapp-parameters.json

stages:
- stage: DeployInfrastructure
  jobs:
  - job: ARM_Deployment
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'SCll01' #informar o nome do Service Connection criado
        subscriptionId: '6e287d78-07f6-4e14-bccc-983b08d4f9f4' #substituir pela subscription Azure
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroupName)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(templateFile)'
        csmParametersFile: '$(parametersFile)'
        deploymentMode: 'Incremental'

- stage: DeployApp
  dependsOn: DeployInfrastructure
  jobs:
  - job: Publish_HTML
    steps:
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'SCll01' #informar o nome do Service Connection criado
        appType: 'webApp'
        appName: 'lmliacpaas001'
        package: 'src'
